using RepoInsight.Domain;

namespace RepoInsight.Analysis;

internal static class TechnologyRules
{
    internal sealed record Dependency(string Ecosystem, string Pattern, string Name, TechnologyCategory Category);

    internal static readonly Dependency[] Dependencies =
    [
        new("nuget", "Microsoft.AspNetCore.*", "ASP.NET Core", TechnologyCategory.Framework),
        new("nuget", "Microsoft.NETCore.App", ".NET", TechnologyCategory.Framework),
        new("nuget", "NETStandard.Library", ".NET", TechnologyCategory.Framework),
        new("npm", "@nestjs/core", "NestJS", TechnologyCategory.Framework),
        new("npm", "express", "Express", TechnologyCategory.Framework),
        new("npm", "@types/node", "Node.js", TechnologyCategory.Framework),
        new("npm", "react", "React", TechnologyCategory.Framework),
        new("npm", "react-native", "React Native", TechnologyCategory.Framework),
        new("npm", "expo", "Expo", TechnologyCategory.Framework),
        new("npm", "next", "Next.js", TechnologyCategory.Framework),
        new("npm", "@angular/core", "Angular", TechnologyCategory.Framework),
        new("npm", "vue", "Vue", TechnologyCategory.Framework),
        new("python", "fastapi", "FastAPI", TechnologyCategory.Framework),
        new("python", "django", "Django", TechnologyCategory.Framework),
        new("python", "flask", "Flask", TechnologyCategory.Framework),
        new("maven", "org.springframework.boot:*", "Spring Boot", TechnologyCategory.Framework),
        new("dart", "flutter", "Flutter", TechnologyCategory.Framework),
        new("npm", "@prisma/client", "Prisma", TechnologyCategory.DataAccess),
        new("npm", "prisma", "Prisma", TechnologyCategory.DataAccess),
        new("nuget", "Microsoft.EntityFrameworkCore", "Entity Framework Core", TechnologyCategory.DataAccess),
        new("nuget", "Microsoft.EntityFrameworkCore.*", "Entity Framework Core", TechnologyCategory.DataAccess),
        new("npm", "sequelize", "Sequelize", TechnologyCategory.DataAccess),
        new("npm", "typeorm", "TypeORM", TechnologyCategory.DataAccess),
        new("npm", "mongoose", "Mongoose", TechnologyCategory.DataAccess),
        new("python", "sqlalchemy", "SQLAlchemy", TechnologyCategory.DataAccess),
        new("maven", "org.hibernate:hibernate-core", "Hibernate", TechnologyCategory.DataAccess),
        new("maven", "org.hibernate.orm:hibernate-core", "Hibernate", TechnologyCategory.DataAccess),
        new("npm", "pg", "PostgreSQL", TechnologyCategory.Database),
        new("npm", "postgres", "PostgreSQL", TechnologyCategory.Database),
        new("nuget", "Npgsql", "PostgreSQL", TechnologyCategory.Database),
        new("nuget", "Npgsql.*", "PostgreSQL", TechnologyCategory.Database),
        new("python", "psycopg", "PostgreSQL", TechnologyCategory.Database),
        new("python", "psycopg2", "PostgreSQL", TechnologyCategory.Database),
        new("python", "psycopg2-binary", "PostgreSQL", TechnologyCategory.Database),
        new("python", "asyncpg", "PostgreSQL", TechnologyCategory.Database),
        new("npm", "mysql", "MySQL", TechnologyCategory.Database),
        new("npm", "mysql2", "MySQL", TechnologyCategory.Database),
        new("nuget", "MySqlConnector", "MySQL", TechnologyCategory.Database),
        new("nuget", "MySql.Data", "MySQL", TechnologyCategory.Database),
        new("nuget", "Pomelo.EntityFrameworkCore.MySql", "MySQL", TechnologyCategory.Database),
        new("python", "pymysql", "MySQL", TechnologyCategory.Database),
        new("python", "mysqlclient", "MySQL", TechnologyCategory.Database),
        new("python", "mysql-connector-python", "MySQL", TechnologyCategory.Database),
        new("maven", "com.mysql:mysql-connector-j", "MySQL", TechnologyCategory.Database),
        new("maven", "mysql:mysql-connector-java", "MySQL", TechnologyCategory.Database),
        new("nuget", "Microsoft.Data.SqlClient", "SQL Server", TechnologyCategory.Database),
        new("nuget", "System.Data.SqlClient", "SQL Server", TechnologyCategory.Database),
        new("nuget", "Microsoft.EntityFrameworkCore.SqlServer", "SQL Server", TechnologyCategory.Database),
        new("npm", "mssql", "SQL Server", TechnologyCategory.Database),
        new("npm", "sqlite3", "SQLite", TechnologyCategory.Database),
        new("npm", "better-sqlite3", "SQLite", TechnologyCategory.Database),
        new("nuget", "Microsoft.Data.Sqlite", "SQLite", TechnologyCategory.Database),
        new("nuget", "Microsoft.EntityFrameworkCore.Sqlite", "SQLite", TechnologyCategory.Database),
        new("nuget", "System.Data.SQLite", "SQLite", TechnologyCategory.Database),
        new("npm", "mongodb", "MongoDB", TechnologyCategory.Database),
        new("npm", "mongoose", "MongoDB", TechnologyCategory.Database),
        new("nuget", "MongoDB.Driver", "MongoDB", TechnologyCategory.Database),
        new("python", "pymongo", "MongoDB", TechnologyCategory.Database),
        new("python", "motor", "MongoDB", TechnologyCategory.Database),
        new("npm", "redis", "Redis", TechnologyCategory.Database),
        new("npm", "ioredis", "Redis", TechnologyCategory.Database),
        new("nuget", "StackExchange.Redis", "Redis", TechnologyCategory.Database),
        new("python", "redis", "Redis", TechnologyCategory.Database),
        new("npm", "firebase", "Firebase", TechnologyCategory.Cloud),
        new("npm", "firebase-admin", "Firebase", TechnologyCategory.Cloud),
        new("dart", "firebase_core", "Firebase", TechnologyCategory.Cloud),
        new("dart", "cloud_firestore", "Firebase", TechnologyCategory.Cloud),
        new("dart", "firebase_database", "Firebase", TechnologyCategory.Cloud),
        new("python", "firebase-admin", "Firebase", TechnologyCategory.Cloud),
        new("nuget", "Azure.*", "Azure", TechnologyCategory.Cloud),
        new("nuget", "Microsoft.Azure.*", "Azure", TechnologyCategory.Cloud),
        new("npm", "@azure/*", "Azure", TechnologyCategory.Cloud),
        new("python", "azure-*", "Azure", TechnologyCategory.Cloud),
        new("npm", "aws-sdk", "AWS", TechnologyCategory.Cloud),
        new("npm", "@aws-sdk/*", "AWS", TechnologyCategory.Cloud),
        new("python", "boto3", "AWS", TechnologyCategory.Cloud),
        new("python", "botocore", "AWS", TechnologyCategory.Cloud),
        new("nuget", "AWSSDK.*", "AWS", TechnologyCategory.Cloud),
        new("npm", "@google-cloud/*", "GCP", TechnologyCategory.Cloud),
        new("python", "google-cloud-*", "GCP", TechnologyCategory.Cloud),
        new("nuget", "Google.Cloud.*", "GCP", TechnologyCategory.Cloud),
        new("nuget", "xunit", "xUnit", TechnologyCategory.Testing),
        new("nuget", "xunit.v3", "xUnit", TechnologyCategory.Testing),
        new("nuget", "NUnit", "NUnit", TechnologyCategory.Testing),
        new("nuget", "MSTest.TestFramework", "MSTest", TechnologyCategory.Testing),
        new("npm", "jest", "Jest", TechnologyCategory.Testing),
        new("npm", "vitest", "Vitest", TechnologyCategory.Testing),
        new("python", "pytest", "Pytest", TechnologyCategory.Testing),
        new("maven", "junit:junit", "JUnit", TechnologyCategory.Testing),
        new("maven", "org.junit.jupiter:junit-jupiter", "JUnit", TechnologyCategory.Testing),
        new("maven", "org.junit.jupiter:junit-jupiter-api", "JUnit", TechnologyCategory.Testing),
        new("npm", "cypress", "Cypress", TechnologyCategory.Testing),
        new("npm", "@playwright/test", "Playwright", TechnologyCategory.Testing),
        new("npm", "playwright", "Playwright", TechnologyCategory.Testing),
        new("nuget", "Microsoft.Playwright", "Playwright", TechnologyCategory.Testing),
        new("python", "playwright", "Playwright", TechnologyCategory.Testing),
        new("nuget", "Swashbuckle.AspNetCore", "Swagger/OpenAPI", TechnologyCategory.ApiIntegration),
        new("nuget", "NSwag.AspNetCore", "Swagger/OpenAPI", TechnologyCategory.ApiIntegration),
        new("nuget", "Microsoft.AspNetCore.OpenApi", "Swagger/OpenAPI", TechnologyCategory.ApiIntegration),
        new("npm", "@nestjs/swagger", "Swagger/OpenAPI", TechnologyCategory.ApiIntegration),
        new("npm", "swagger-ui-express", "Swagger/OpenAPI", TechnologyCategory.ApiIntegration),
        new("npm", "swagger-jsdoc", "Swagger/OpenAPI", TechnologyCategory.ApiIntegration),
        new("npm", "graphql", "GraphQL", TechnologyCategory.ApiIntegration),
        new("npm", "@apollo/server", "GraphQL", TechnologyCategory.ApiIntegration),
        new("npm", "@apollo/client", "GraphQL", TechnologyCategory.ApiIntegration),
        new("nuget", "GraphQL", "GraphQL", TechnologyCategory.ApiIntegration),
        new("nuget", "HotChocolate.AspNetCore", "GraphQL", TechnologyCategory.ApiIntegration),
        new("nuget", "Grpc.AspNetCore", "gRPC", TechnologyCategory.ApiIntegration),
        new("nuget", "Grpc.Net.Client", "gRPC", TechnologyCategory.ApiIntegration),
        new("npm", "@grpc/grpc-js", "gRPC", TechnologyCategory.ApiIntegration),
        new("python", "grpcio", "gRPC", TechnologyCategory.ApiIntegration),
        new("npm", "stripe", "Stripe", TechnologyCategory.ApiIntegration),
        new("npm", "@stripe/stripe-js", "Stripe", TechnologyCategory.ApiIntegration),
        new("nuget", "Stripe.net", "Stripe", TechnologyCategory.ApiIntegration),
        new("python", "stripe", "Stripe", TechnologyCategory.ApiIntegration),
        new("cargo", "tokio-postgres", "PostgreSQL", TechnologyCategory.Database),
        new("cargo", "postgres", "PostgreSQL", TechnologyCategory.Database),
        new("cargo", "redis", "Redis", TechnologyCategory.Database),
        new("cargo", "mongodb", "MongoDB", TechnologyCategory.Database),
        new("go", "github.com/lib/pq", "PostgreSQL", TechnologyCategory.Database),
        new("go", "github.com/jackc/pgx/v5", "PostgreSQL", TechnologyCategory.Database),
        new("go", "github.com/go-sql-driver/mysql", "MySQL", TechnologyCategory.Database),
        new("go", "google.golang.org/grpc", "gRPC", TechnologyCategory.ApiIntegration),
    ];

    internal static readonly IReadOnlyDictionary<string, string> Languages = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        [".cs"] = "C#",
        [".ts"] = "TypeScript",
        [".tsx"] = "TypeScript",
        [".mts"] = "TypeScript",
        [".cts"] = "TypeScript",
        [".js"] = "JavaScript",
        [".jsx"] = "JavaScript",
        [".mjs"] = "JavaScript",
        [".cjs"] = "JavaScript",
        [".py"] = "Python",
        [".pyi"] = "Python",
        [".java"] = "Java",
        [".cpp"] = "C++",
        [".cc"] = "C++",
        [".cxx"] = "C++",
        [".hpp"] = "C++",
        [".hh"] = "C++",
        [".hxx"] = "C++",
        [".c"] = "C",
        [".go"] = "Go",
        [".rs"] = "Rust",
        [".sql"] = "SQL",
        [".kt"] = "Kotlin",
        [".kts"] = "Kotlin",
        [".swift"] = "Swift",
        [".php"] = "PHP",
        [".rb"] = "Ruby",
        [".dart"] = "Dart",
        [".html"] = "HTML",
        [".htm"] = "HTML",
        [".css"] = "CSS",
        [".scss"] = "SCSS",
        [".sh"] = "Shell",
        [".bash"] = "Shell",
        [".zsh"] = "Shell",
        [".ps1"] = "PowerShell",
        [".psm1"] = "PowerShell",
        [".psd1"] = "PowerShell",
    };
}

